[pytest]
; addopts 忽略 UnsupportedWarning
addopts = -p no:warnings -k normal -vs --reruns 0 --reruns-delay 5 --self-contained-html --capture sys
testpaths = ./testcase
python_files = test*.py
python_classes = Test*
python_functions = test*
render_collapsed = True
markers =
    smoke: 冒烟测试用例
    normal: 正常用例
